languageCode = "en-us"
title = ""
baseURL = "https://mslasercutter.netlify.com"
theme = "hugo-theme-dopetrope"
hidesidebar = "true"

[params.portfolio]
    title = "Earrings"
    foldername = "portfolio"
    findoutmoretext = "Find out more"

[params.blog]
    title = ""
    viewalltext = ""
    foldername = ""

[params.settings]
    googleanalytics = "UA-124960515-1"
    disqus = "hugo-dopetrope"
    
[social]
  instagram = "https://www.instagram.com/mslasercutter/"
